# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-JSON
version:      0.01
version_from: JSON.pm
installdirs:  site
requires:
    Carp:                          
    JSON:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
