# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-JSON
version:      0.03
version_from: lib/POE/Filter/JSON.pm
installdirs:  site
requires:
    Carp:                          
    JSON::Any:                     1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
